title:友元、异常和其他
date: 2021-06-17  14:48

---

### 友元p602

- 除了友元函数还有友元类，并且可以将**类的特定成员函数**指定为另一个类的友元

- 友元声明可以位于公有、私有、保护部分，**其所在位置无关紧要**

- 友元类

  - 定义如下

    ```c++
    class Tv
    {
        friend class Remote;
    };
    class Remote
    {
        ...
    public:
        bool volup(Tv &v) { return v.volup(); }
    };
    ```
    
  - Remote作为Tv的友元类，可以直接访问Tv的私有部分

  - 由于Remote提到了Tv类，所以Tv要在Remote前定义

- 友元成员函数p608

  - 仅让一个成员函数作为类的友元，可以直接访问私有部分

    ```c++
    class Tv
    {
        friend void Remote::set_chan(Tv& v, int c);
    };
    ```

  - 这种情况需要让编译器知道`Remote::set_chan`函数，所以要将Remote的定义放到Tv前面

    这会造成循环依赖，因此可以采用向前声明

    ```c++
    class Tv; //forward declaration
    class Remote {...};
    class Tv {...};
    ```

    但是Remote中的内联代码调用了Tv中的方法，这有需要Tv类方法声明在Remote的内联代码之前，解决方法是不内联

    ```c++
    class Tv; //forward declaration
    class Remote {...}; //Tv-using methods as prototypes only
    class Tv {...};
    //put Remote method definitions here
    bool Remote::volup(Tv &v) { return v.volup(); }
    //如果还是需要inline可以加关键字限定
    inline bool Remote::volup(Tv &v) { return v.volup(); }
    ```
  
- 互为友元p609

  ```c++
  class Remote;
  class Tv
  {
      friend class Remote;
  public:
      void buzz(Remote &r);
  };
  class Remote
  {
      friend class Tv;
      ...
  public:
      bool volup(Tv &v) { return v.volup(); }
  };
  inline void buzz(Remote &r) { ... };
  ```

- 共同的友元p610

  ```c++
  class Analyzer;
  class Probe
  {
      friend void sync(Analyzer& a, const Probe& p); //sync a to p
      friend void sync(Probe& a, const Analyzer& p); //sync p to a
  };
  class Analyzer
  {
      friend void sync(Analyzer& a, const Probe& p); //sync a to p
      friend void sync(Probe& a, const Analyzer& p); //sync p to a
  };
  //define
  void sync(Analyzer& a, const Probe& p)
  {
      ...
  }
  void sync(Probe& a, const Analyzer& p)
  {
      ...
  }
  ```

---

### 嵌套类p611

- 嵌套类访问权限

  ```c++
  class Queue 
  {
      class Node
      {
          ...
      public:
          Node(const Item& i);
      };
  private:
      ...
  };
  Queue::Node::Node(const Item& i)
  {
      ...
  }
  ```

  - Queue成员可以使用Node对象和指向Node的指针，但是程序的其他部分甚至不知道Node的存在

    （**类的默认访问权限是私有的**，即使Node是在Queue的privte部分之前定义的）

  - 如果Node是在公有部分定义的，则允许Queue、其派生类，以及外部世界使用，但是在外部世界需要使用类限定符
  
    ```c++
    class Queue 
    {
    public:
        class Node
        {
    		...
        };
    	...
    };
    Queue::Node qn;
    ```
  
  - Queue类对象只能显示的访问Node对象的公有成员（**即对嵌套类访问权的控制规则与对常规类相同**）
  
    可以考虑将Node类全部公有，因为外部不可见

---

### 异常p616

- tip：新式编译器将无穷大用一个特殊浮点数表示，`cout`将其处理成`INF,inf,Inf`之类的东西
- 发生异常的处理办法
    - 调用`abort()`
      - 其典型操作是向标准错误流（cerr使用的错误流）发送消息abnormal program termination（程序异常终止），然后终止程序
      
        返回一个随实现而异的值，告诉操作系统或父进程处理失败
      
      - `abort()`将程序直接终止，而不是先返回到`main()`
      
    - 返回错误码

      - 将可能出现错误的程序定义为`bool,int`等类型，并为每一个返回值定义其意义

        ```c++
        bool div(int x, int y, int *r)
        {
            if (y == 0)
                return 1; //failure
            else
                *r = x / y;
           	return 0; //success
        }
        ```

        第三参数可以是指针或引用，对于内置类型的参数，倾向于用指针，因为可以明显看出是哪个参数用于提供答案

      - 另一种是将返回条件储存在全局变量中，如传统c语言的数学库就使用这种办法，全局变量名为`errno`

    - 异常机制p619

      - 组成部分：引发异常，使用处理程序捕获异常，使用try块

        ```c++
        try
        {
            z = div(x, y);
        }
        catch (char *s) //捕获异常
        {
            std::cout << s <<std::endl;
            return 0;
        }
        
        int div(int x, int y)
        {
            if (y == 0)
                throw "Error!"; //引发异常
            else
                return x / y;
        }
        ```

        - 如果引发异常的部分在try外，则catch不到异常`char* s`表示捕获字符串异常，即throw出来的是一个字符串

        - 如果没有异常，则跳过catch块

        - 如果引发了异常，而没有try块或者没有匹配的处理程序，在默认情况下会调用`abort()`函数

---

### 将对象用作异常p620

- 可以在异常里携带更多信息

  ```c++
  class bad
  {
  private:
      int v1;
      int v2;
  public:
      bad(int a, int b) : v1(a), v2(b) {};
      void what() { std::cout << "v1:" << a << " v2:" << b << std::endl; }
  }
  
  try
  {
      z = div(x, y);
  }
  catch (bad &b) //捕获异常
  {
      b.what();
      return 0;
  }
  
  int div(int x, int y)
  {
      if (y == 0)
          throw bad(x, y); //引发异常
      else
          return x / y;
  }
  ```
- 基类异常和派生类异常p629
    - 引发异常时编译器总是创建一个临时拷贝

      ```c++
      int div(int x, int y)
      {
          if (y == 0)
              throw bad(x, y); //引发异常
          else
              return x / y;
      }
      
      catch (bad &b) //此处的b指向上面bad(x, y)的副本而不是其本身
      {
          b.what();
          return 0;
      }
      ```
      
      首先其本身会由于`div()`函数的结束而被析构，其次b可以指向派生类异常
      
    - `exception`类

      - 头文件`<exception>`

      - 包含一个`what()`的虚函数，返回一个字符串

      - 捕获所有派生异常

      ```c++
      catch (std::exception& e)
      ```

         - `stdexcept`异常类

            - 构造函数接受一个string对象作为参数，提供方法`what()`用作返回的C-风格字符串
              ```c++
              class logic_error : public exception //派生类
              {
              public:
                explicit logic_error(const string& what_arg);
                ...
              };
              ```

            - `logic_error`类：典型逻辑错误，可以通过合理变成避免这种错误
              - `domain_error`：超出函数定义域引发错误
              - `invalid_argument`：给函数传了一个意料之外的值
              - `length_error`：没有足够空间来执行所需要的操作
              - `out_of_bound`：索引错误
            - `runtime_error`类：运行期间发生但难以预计和防范的错误
              - `range_error`：计算结果不在函数的允许范围内，但没有发生上溢或下溢
              - `overflow_erroe`：上溢错误
              - `underflow_error`：下溢错误
            - `bad_alloc`和`new`
              - 对于`new`导致的内存分配问题，无法分配请求的内存量时，引发`bad_alloc`异常
            
              - 曾今是让`new`返回一个空指针，有些编译器提供了一个选择
            
                ```c++
                int *pi = new (std::nothrow) int; //失败时返回空指针
                ```
      
        - 捕获任意异常
      
          ```c++
          catch (...) { dosomething(); } //就是...这么写的
          ```
---

### 异常规范和c++11 p624

- 语法

  ```c++
  double harm(double a) throw(bad_thing); //may throw bad_thing exception
  double harm(double) throw(); //doesn't throw an exception
  ```

  - 其中的`throw()`是异常规范，他可能出现在函数原型和函数定义中，可包含类型列表，也可不包含。
    
  - 异常规范可以**告诉用户可能需要使用try块**，也告诉编译器添加执行运行阶段检查的代码，检查是否违反了异常规范，但这**很难检查**
    
  - c++11中建议忽略异常规范，但可以使用新增关键字`noexcept`指出函数不会引发异常
    ```c++
    double marm() noexcept; //marm() doesn't throw an excception
    ```
    
    这有助于编译器优化代码，并且这相当于程序员“承诺”不会引发异常
    
  - 运算符`noexcept()`判断其操作数是否会引发异常

---

### 栈解退p625

- `return()`返回至上一个调用处，通过存储在栈中的地址信息获得第一个地址信息并返回

- 出现异常而终止时，程序**也将释放栈中的内存**，但不会在释放栈的第一个地址就直接返回，**而是继续释放栈**，直到遇到第一个try块

  **随后控制权转到块尾的异常处理程序，而不是函数调用后的第一条语句**，对于栈中的**自动类对象**（即不是new出来的），将会自动调用析构函数

- `return()`处理该函数放在栈中的对象，而异常终止处理`try`到`throw`之间的所有栈中对象

- 重新引发异常

  ```c++
  catch (bad1& b1)
  {
  b1.what();
  throw; //rethrows the exception
  }
  ```

  通过`throw`重新引发异常往上传递，即希望在中间进行一次处理在将处理权交给`main()`时可以采用这种做法，**`throw`之后的代码也不会运行**

---

### 更改异常处理p639

- 如果异常是在**有异常规范**的函数中被引发，则必须与规范列表中的某种异常匹配，不然在默认情况下会导致程序异常终止（即没有try块或者没有匹配的catch块）先调用`terminate()`，`terminate()`调用`abort()`
  
- 通过调用`set_terminate()`来更改程序行为，默认情况下`set_terminate()`调用`abort()`函数
  
  ```c++
              typedef void (*terminate_handler)();
              //using terminate_handler = void(*)()
              terminate_handler set_terminate(terminate_handler f) noexcept; //c++11
              void terminate() noexcept; //c++11
  ```
  
  - 如果`A()`中调用了`B()`，`B()`中的异常规范应该被包含在`A()`中，但用库不能保证这一点
  
    则如果函数引发了其异常规范中没有的异常，则会调用`unexpected()`函数，而`unexpected()`会调用`terminate()`
  
  - 同样可以修改`unexpected()`的行为
    
    ```c++
    typedef void (*unexpected_handler)();
    //using unexpected_handler = void(*)()
    unexpected_handler set_unexpected(unexpected_handler f) noexcept; //c++11
    void unexpected() noexcept; //c+0x
    ```
    
    - 但`unexpected_handler`程序有着严格限制，只能有下面两种行为
      - 调用`terminate(),abort(),exit()`来终止程序
      - 引发异常
          - 如果新引发的异常与原来的异常规范**匹配**，则开始寻找catch块
          - 如果新引发的异常与原来的异常规范**不匹配**，且异常规范中**没有**`std::bad_exception`类型，则调用`terminate()`
          - 如果新引发的异常与原来的异常规范**不匹配**，且异常规范中**有**`std::bad_exception`类型，则不匹配的异常被其取代
  
- 要捕获所有的异常，包括预期异常和意外异常
  ```c++
  #include <exception>
  //将意外异常转为bad_exception异常
  void myUnexpected()
  {
  throw std::bad_exception();
  }
  set_unexpected(myUnexpected);
  //捕获异常
  try
  {
  ...
  }
  catch(something)
  {
  ...
  }
  catch(std::bad_exception& be)
  {
  ...
  }
  ```

---

### 一些注意事项p641

- `new`造成的内存泄漏（可以避免），在引发异常的函数中捕获该异常，清理掉该清理的内存，然后重新引发异常

  ```c++
  void test3(int n)
  {
      double* ar = new double[n];
      try
      {
          if (oh_no)
              throw exception();
      }
      catch (exception& e)
      {
          delete[] ar;
          throw;
      }
      ...
      delete[] ar;
  }
  ```

---

### RTTI p642

- 为程序在运行阶段确认对象类型的一种标准方式（考虑基类指针指向派生对象），只能用于包含虚函数的层次结构

- `dynamic_cast`运算符

  ```c++
  A a;
  BaseA* p = (BaseA*)(&a); //c语法
  BaseA* p = dynamic_cast<BaseA*>(&a); //c++
  ```

  - 使用一个指向基类的指针来生成一个指向派生类的指针，否则返回空指针

    ```c++
    if (p = dynamic_cast<BaseA*>(&a))//赋值表达式的值是他左边的值
        p->Say();//BaseA基类方法
    ```

  - 能够回答“是够可以安全的将对象的地址赋给特定类型的指针”的问题

  - 若将`dynamic_cast`用于引用，当失败是没有空引用，而是引发一个`bad_cast`异常

- `typeid`运算符返回一个指出对象的类型的值

  ```c++
  typeid(A) == typeid(*pa); //如果pa指向的对象是A类的则为true
  ```

- `type_info`结构储存了有关特定类型的信息，一般包含`name()`方法用于返回类的名称

---

### 类型转换运算符p651

- `dynamic_cast`

  - 能够在类层次中进行向上cast

- `const_cast`

  - 改变值为const或volatile，原类型和目标类型除了const或volatile不同，其他必须相同，通用转换也能实现，但是不够安全

    ```c++
  int c = 5;
  const int *ca = &c;
  int *a = const_cast<int*>(ca); //valid
  *a = 10;
  double *d = const_cast<int*>(ca); //invalid
    ```

  - 他可以修改指向一个值的指针，但修改const值的结果是不确定的

    ```c++
    const int a = 2000;
    int *pa = const_cast<int*>(&a);
    *pa += 200; //并不会改变a的值,也不会报错
    //但是*pa的值已经变成了2200
    //或者如下
    const int a = 2000;
    const int *cpa = &a
    int *pa = const_cast<int*>(&cpa);
    *pa += 200; //*pa和*cpa的值都是2200,但是a的值不会改变
    ```
    

- `static_cast`

  - 仅当**双方类型**其中一方可隐式转换为另一方时，该转换合法

    ```c++
    int a = 1;
    double d = static_cast<double>(a);
    
    A a;
    BaseA ba;
    BaseA* pba = static_cast<BaseA*>(&a);
    A* pa = static_cast<A*>(&ba); //基类指针转为派生类指针,即派生类指针指向基类对象
    ```

    **第二种转换在不进行显式类型转换的情况下将无法进行，但是因为另一个方向的转换（即派生类指针到基类指针）可以隐式转换，所有表达式合法**

- `reinterpret_cast`

  - 用于天生危险的类型转换，用于实现奇奇怪怪的操作

    ```c++
    struct dat { short a; short b; };
    long value = 0xA224B118;
    dat* pd = reinterpret_cast<dat*>(&value);
    std::cout << hex << pd->a; //display first 2 bytes of value
    ```

  - 并不支持所有的类型转换

    - 可以将指针类型转为整型，但不能转换为更小的整型或浮点型
    - 不能将函数指针转换为数据指针，反之亦然

---

已完结 2021.6.18

